#pragma once
#include <SDL.h>

#include <memory>
#include <unordered_set>

#include "IMapView.h"

/**
 * WindowRenderer implements the IMapView protocol,
 * while being attached to a specific SDL_Renderer.
 *
 * Doesn't assume ownership of that Renderer, and doesn't free it!
 */
class WindowRenderer : public IMapView {
   private:
    SDL_Renderer*& m_attached_renderer;

   public:
    WindowRenderer(SDL_Renderer*& renderer) : m_attached_renderer(renderer) {}
    void before_render() override;
    void render(IMapObject*) override;
    void after_render() override;
};

/**
 * Window represents a main Window
 */
class Window {
   private:
    SDL_Window* m_sdl_window{NULL};
    SDL_Renderer* m_renderer{NULL};
    std::unordered_set<SDL_Keycode> m_pressed_keys{};
    int m_width{-1};
    int m_height{-1};
    bool m_is_running{false};

   public:
    ~Window();

    /**
     * Creates and connects to a SDLWindow and a Renderer
     */
    void init(const char* title = "PROI Auto", int width = 800,
              int height = 600, bool fullscreen = false);

    /**
     * Helper function to load an SDL_Texture from a file
     */
    SDL_Texture* load_texture(const char* file);

    /**
     * Handles all events generated by SDL
     */
    void handleEvents();

    /**
     * Destroys all connections with SDL
     */
    void clean();

    /**
     * Checks whether a key is pressed
     */
    inline bool is_pressed(SDL_Keycode key) {
        return m_pressed_keys.find(key) != m_pressed_keys.end();
    }

    /**
     * Creates a WindowRenderer attached to this Window
     */
    inline std::unique_ptr<IMapView> create_mapview() {
        return std::unique_ptr<IMapView>(new WindowRenderer(m_renderer));
    }

    inline SDL_Renderer* get_renderer() { return m_renderer; }
    inline int get_width() { return m_width; }
    inline int get_height() { return m_height; }
    inline bool is_running() { return m_is_running; }
};
